### PR TITLE
Lobster clean

### PR DESCRIPTION
**Pull request by naik-aakash**
## Summary

Hi @JaGeo , Following changes have been made

1. Added a working schema for LOBSTER tasks, that stores lobsterpy data, LOBSTER charges, Strongest ICOBI,ICOOP, ICOHP along with COOP, COHP, COBI data objects in the DB
2.  Fixed the delete_wavecar firework fizzled issue. Now workflow runs through completely and deletes the wavecars.
3. Renamed the fireworks corresponding to actual task being performed.

After your review, will also add an option to perform lobsterpy analysis with all bonds option when no cation-anion are detected.

### CODE REVIEW

**Comment by JaGeo** [comment]
Wow! Thanks! This is so awesome. I will review as soon as possible and merge it into our pull-request 😍.

Now: Happy weekend 😉

**Comment by naik-aakash** [comment]
> Wow! Thanks! This is so awesome. I will review as soon as possible and merge it into our pull-request 😍.
> 
> Now: Happy weekend 😉

You are welcome. And Thanks! Happy weekend to you too :smiley:

**Comment by JaGeo** [comment]
One tiny suggestion for next week (before I forget): maybe, we could add Lobster DOS as well (also in data=...)

**Comment by JaGeo** [comment]
I am merging it for now so that Alex sees that we are working on it and we will further refine from there.

**Pull request merged**
